/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotl;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author jerry
 */
public class MantenimientodeClientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientodeClientes.class.getName());

    /**
     * Creates new form MantenimientodeClientes
     */
    public MantenimientodeClientes() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CedulaLabel = new javax.swing.JLabel();
        Nombrelabel = new javax.swing.JLabel();
        Apellidoslabel = new javax.swing.JLabel();
        Direccionlabel = new javax.swing.JLabel();
        Emaillabel = new javax.swing.JLabel();
        Telefonolabel = new javax.swing.JLabel();
        buscacliente = new javax.swing.JButton();
        GuardarCliente = new javax.swing.JButton();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        eliminarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CedulaLabel.setText("Cedula:");

        Nombrelabel.setText("Nombre:");

        Apellidoslabel.setText("Apellidos:");

        Direccionlabel.setText("Direccion:");

        Emaillabel.setText("Email:");

        Telefonolabel.setText("Telefono:");

        buscacliente.setText("Buscar Cliente");
        buscacliente.addActionListener(this::buscaclienteActionPerformed);

        GuardarCliente.setText("Guardar");
        GuardarCliente.addActionListener(this::GuardarClienteActionPerformed);

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
        });

        eliminarCliente.setText("Eliminar ");
        eliminarCliente.addActionListener(this::eliminarClienteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CedulaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Apellidoslabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Direccionlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Emaillabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Telefonolabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombrelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedula)
                            .addComponent(txtNombre)
                            .addComponent(txtApellidos)
                            .addComponent(txtDireccion)
                            .addComponent(txtEmail)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscacliente)
                        .addGap(32, 32, 32)
                        .addComponent(GuardarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(eliminarCliente)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CedulaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombrelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellidoslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefonolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscacliente)
                    .addComponent(GuardarCliente)
                    .addComponent(eliminarCliente))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarClienteActionPerformed

// Validacion de datos...
    try {
        // CREAR ARCHIVO SI NO EXISTE
        File archivo = new File("clientes.txt");

        if(!archivo.exists()){
            archivo.createNewFile();
        }

        File temp = new File("temp.txt");

        BufferedReader br = new BufferedReader(new FileReader(archivo));
        BufferedWriter bw = new BufferedWriter(new FileWriter(temp));

        String linea;
        boolean encontrado = false;

        while((linea = br.readLine()) != null){
            String datos[] = linea.split(",");

            if(datos[0].equals(txtCedula.getText())){
                linea = txtCedula.getText() + "," +
                        txtNombre.getText() + "," +
                        txtApellidos.getText() + "," +
                        txtDireccion.getText() + "," +
                        txtEmail.getText() + "," +
                        txtTelefono.getText();
                encontrado = true;
            }

            bw.write(linea);
            bw.newLine();
        }

        if(!encontrado){
            String nueva = txtCedula.getText() + "," +
                           txtNombre.getText() + "," +
                           txtApellidos.getText() + "," +
                           txtDireccion.getText() + "," +
                           txtEmail.getText() + "," +
                           txtTelefono.getText();

            bw.write(nueva);
            bw.newLine();
        }

        br.close();
        bw.close();

        archivo.delete();
        temp.renameTo(archivo);

        JOptionPane.showMessageDialog(null, "Guardado correctamente");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarClienteActionPerformed

    private void buscaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaclienteActionPerformed
        // TODO add your handling code here:

    // VALIDAR QUE NO ESTÉ VACÍO
    if(txtCedula.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Digite la cédula");
        return;
    }

    try {
        File archivo = new File("clientes.txt");

        // CREAR ARCHIVO SI NO EXISTE
        if(!archivo.exists()){
            archivo.createNewFile();
        }

        BufferedReader br = new BufferedReader(new FileReader(archivo));
        String linea;
        boolean encontrado = false;

        while((linea = br.readLine()) != null){
            String datos[] = linea.split(",");

            if(datos[0].equals(txtCedula.getText())){
                
                // CARGAR DATOS EN LOS CAMPOS
                txtNombre.setText(datos[1]);
                txtApellidos.setText(datos[2]);
                txtDireccion.setText(datos[3]);
                txtEmail.setText(datos[4]);
                txtTelefono.setText(datos[5]);

                JOptionPane.showMessageDialog(null, "Cliente encontrado");
                encontrado = true;
                break;
            }
        }

        br.close();

        if(!encontrado){
            JOptionPane.showMessageDialog(null, "Cliente no existe");

            // LIMPIAR CAMPOS
            txtNombre.setText("");
            txtApellidos.setText("");
            txtDireccion.setText("");
            txtEmail.setText("");
            txtTelefono.setText("");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
 
    }//GEN-LAST:event_buscaclienteActionPerformed

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased

    try {
        File archivo = new File("clientes.txt");

        // Crear archivo si no existe
        if(!archivo.exists()){
            archivo.createNewFile();
        }

        BufferedReader br = new BufferedReader(new FileReader(archivo));
        String linea;
        boolean encontrado = false;

        while((linea = br.readLine()) != null){
            String datos[] = linea.split(",");

            if(datos[0].equals(txtCedula.getText())){
                // CARGAR DATOS
                txtNombre.setText(datos[1]);
                txtApellidos.setText(datos[2]);
                txtDireccion.setText(datos[3]);
                txtEmail.setText(datos[4]);
                txtTelefono.setText(datos[5]);

               
                encontrado = true;
                break;
            }
        }

        br.close();

        if(!encontrado){
            
            // LIMPIAR CAMPOS (IMPORTANTE)
            txtNombre.setText("");
            txtApellidos.setText("");
            txtDireccion.setText("");
            txtEmail.setText("");
            txtTelefono.setText("");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }        
        
      // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void eliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClienteActionPerformed
// eliminar datos del cliente.

    if(txtCedula.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Digite la cédula");
        return;
    }

    try {
        File archivo = new File("clientes.txt");
        File temp = new File("temp.txt");

        BufferedReader br = new BufferedReader(new FileReader(archivo));
        BufferedWriter bw = new BufferedWriter(new FileWriter(temp));

        String linea;
        boolean eliminado = false;

        while((linea = br.readLine()) != null){
            String datos[] = linea.split(",");

            if(datos[0].equals(txtCedula.getText())){
                eliminado = true;
                continue; // 🔥 NO lo escribe (lo elimina)
            }

            bw.write(linea);
            bw.newLine();
        }

        br.close();
        bw.close();

        archivo.delete();
        temp.renameTo(archivo);

        if(eliminado){
            JOptionPane.showMessageDialog(null, "Cliente eliminado");

            // LIMPIAR CAMPOS
            txtCedula.setText("");
            txtNombre.setText("");
            txtApellidos.setText("");
            txtDireccion.setText("");
            txtEmail.setText("");
            txtTelefono.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Cliente no existe");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantenimientodeClientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidoslabel;
    private javax.swing.JLabel CedulaLabel;
    private javax.swing.JLabel Direccionlabel;
    private javax.swing.JLabel Emaillabel;
    private javax.swing.JButton GuardarCliente;
    private javax.swing.JLabel Nombrelabel;
    private javax.swing.JLabel Telefonolabel;
    private javax.swing.JButton buscacliente;
    private javax.swing.JButton eliminarCliente;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
