/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotl;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author jerry
 */
public class MantenimientodeClientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientodeClientes.class.getName());

    /**
     * Creates new form MantenimientodeClientes
     */
    public MantenimientodeClientes() {
     
    initComponents();
     buscacliente.setEnabled(false);
    GuardarCliente.setEnabled(false);
    eliminarCliente.setEnabled(false);
    
  
    }  
    private boolean camposLlenos(){

    return !txtCedula.getText().isEmpty() &&
           !txtNombre.getText().isEmpty() &&
           !txtApellidos.getText().isEmpty();
}
    
    private void reset(){

    txtCedula.setText("");
    txtNombre.setText("");
    txtApellidos.setText("");
    txtDireccion.setText("");
    txtTelefono.setText("");
    txtEmail.setText("");

    buscacliente.setEnabled(false);
     GuardarCliente.setEnabled(false);
    eliminarCliente.setEnabled(false);
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombrelabel = new javax.swing.JLabel();
        Emaillabel = new javax.swing.JLabel();
        Telefonolabel = new javax.swing.JLabel();
        buscacliente = new javax.swing.JButton();
        GuardarCliente = new javax.swing.JButton();
        txtCedula = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        Bg = new javax.swing.JPanel();
        CedulaLabel = new javax.swing.JLabel();
        Apellidoslabel = new javax.swing.JLabel();
        Direccionlabel = new javax.swing.JLabel();
        eliminarCliente = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nombrelabel.setText("Nombre:");

        Emaillabel.setText("Email:");

        Telefonolabel.setText("Telefono:");

        buscacliente.setText("Buscar Cliente");
        buscacliente.addActionListener(this::buscaclienteActionPerformed);

        GuardarCliente.setText("Guardar");
        GuardarCliente.addActionListener(this::GuardarClienteActionPerformed);

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
        });

        Bg.setForeground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CedulaLabel.setText("Cedula:");

        Apellidoslabel.setText("Apellidos:");

        Direccionlabel.setText("Direccion:");

        eliminarCliente.setText("Eliminar ");
        eliminarCliente.addActionListener(this::eliminarClienteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Telefonolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Direccionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(buscacliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuardarCliente))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(CedulaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Nombrelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Apellidoslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(eliminarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CedulaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombrelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellidoslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefonolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscacliente)
                    .addComponent(GuardarCliente))
                .addGap(18, 18, 18)
                .addComponent(eliminarCliente)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarClienteActionPerformed

// Validacion de datos.
   
if(!camposLlenos()){
    JOptionPane.showMessageDialog(null, "Complete los campos");
    return;
}
    try {
        // CREAR ARCHIVO SI NO EXISTE
        File archivo = new File("clientes.txt");

        if(!archivo.exists()){
            archivo.createNewFile();
        }

        File temp = new File("temp.txt");

        BufferedReader br = new BufferedReader(new FileReader(archivo));
        BufferedWriter bw = new BufferedWriter(new FileWriter(temp));

        String linea;
        boolean encontrado = false;

        while((linea = br.readLine()) != null){
            String datos[] = linea.split(",");

            if(datos[0].equals(txtCedula.getText())){
                linea = txtCedula.getText() + "," +
                        txtNombre.getText() + "," +
                        txtApellidos.getText() + "," +
                        txtDireccion.getText() + "," +
                        txtEmail.getText() + "," +
                        txtTelefono.getText();
                encontrado = true;
            
          
            }
             
            bw.write(linea);
            bw.newLine();
        }

        if(!encontrado){
            String nueva = txtCedula.getText() + "," +
                           txtNombre.getText() + "," +
                           txtApellidos.getText() + "," +
                           txtDireccion.getText() + "," +
                           txtEmail.getText() + "," +
                           txtTelefono.getText();

            bw.write(nueva);
            bw.newLine();
        }

        br.close();
        bw.close();

        archivo.delete();
        temp.renameTo(archivo);

        JOptionPane.showMessageDialog(null, "Guardado correctamente");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
reset();
    }//GEN-LAST:event_GuardarClienteActionPerformed

    private void buscaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaclienteActionPerformed

    try {
        BufferedReader br = new BufferedReader(new FileReader("clientes.txt"));
        String linea;

        boolean encontrado = false; 

        while((linea = br.readLine()) != null){
            String datos[] = linea.split(",");

            if(datos[0].equals(txtCedula.getText())){

                txtNombre.setText(datos[1]);
                txtApellidos.setText(datos[2]);
                txtDireccion.setText(datos[3]);
                txtTelefono.setText(datos[4]);
                txtEmail.setText(datos[5]);

                encontrado = true;
                break;
            }
        }

        br.close();

        //  AQUÍ DECIDE EL SISTEMA
        if(encontrado){

            JOptionPane.showMessageDialog(null, "Cliente encontrado");

            GuardarCliente.setEnabled(true);
            eliminarCliente.setEnabled(true);

        } else {

            JOptionPane.showMessageDialog(null, "Cliente no encontrado");

            txtNombre.setText("");
            txtApellidos.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtEmail.setText("");

            GuardarCliente.setEnabled(true);
            eliminarCliente.setEnabled(false);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error");
    }

    }//GEN-LAST:event_buscaclienteActionPerformed

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
    
        
        if(txtCedula.getText().trim().isEmpty()){
        buscacliente.setEnabled(false);
    } else {
         buscacliente.setEnabled(true);
    }

    // bloquear los otros mientras escribe
     GuardarCliente.setEnabled(false);
    eliminarCliente.setEnabled(false); 
  
    try {
        File archivo = new File("clientes.txt");

        // Crear archivo si no existe
        if(!archivo.exists()){
            archivo.createNewFile();
        }

        BufferedReader br = new BufferedReader(new FileReader(archivo));
        String linea;
        boolean encontrado = false;

        while((linea = br.readLine()) != null){
            String datos[] = linea.split(",");

           // if(datos[0].equals(txtCedula.getText())){
                // CARGAR DATOS
                //txtNombre.setText(datos[1]);
                //txtApellidos.setText(datos[2]);
                //txtDireccion.setText(datos[3]);
               // txtEmail.setText(datos[4]);
                //txtTelefono.setText(datos[5]);

               
                encontrado = true;
                break;
           // }
        }

        br.close();

        if(!encontrado){
            
            // LIMPIAR CAMPOS 
            txtNombre.setText("");
            txtApellidos.setText("");
            txtDireccion.setText("");
            txtEmail.setText("");
            txtTelefono.setText("");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }        
        
      // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void eliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClienteActionPerformed
// eliminar datos del cliente.

    if(txtCedula.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Digite la cédula");
        return;
    }

    try {
        File archivo = new File("clientes.txt");
        File temp = new File("temp.txt");

        BufferedReader br = new BufferedReader(new FileReader(archivo));
        BufferedWriter bw = new BufferedWriter(new FileWriter(temp));

        String linea;
        boolean eliminado = false;

        while((linea = br.readLine()) != null){
            String datos[] = linea.split(",");

            if(datos[0].equals(txtCedula.getText())){
                eliminado = true;
                continue;  //  NO lo escribe (lo elimina)
            }

            bw.write(linea);
            bw.newLine();
        }

        br.close();
        bw.close();

        archivo.delete();
        temp.renameTo(archivo);

        if(eliminado){
            JOptionPane.showMessageDialog(null, "Cliente eliminado correctamente");

            // LIMPIAR CAMPOS
            txtCedula.setText("");
            txtNombre.setText("");
            txtApellidos.setText("");
            txtDireccion.setText("");
            txtEmail.setText("");
            txtTelefono.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Cliente no existe");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantenimientodeClientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidoslabel;
    private javax.swing.JPanel Bg;
    private javax.swing.JLabel CedulaLabel;
    private javax.swing.JLabel Direccionlabel;
    private javax.swing.JLabel Emaillabel;
    private javax.swing.JButton GuardarCliente;
    private javax.swing.JLabel Nombrelabel;
    private javax.swing.JLabel Telefonolabel;
    private javax.swing.JButton buscacliente;
    private javax.swing.JButton eliminarCliente;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
